### PR TITLE
SignmodeDirect, refact. EstimatedFeeWithoutBurnTax changed to async

### PR DESCRIPTION
**Pull request by marcwlux**
now SignmodeDirect, 
refact. EstimatedFeeWithoutBurnTax changed to async

### CODE REVIEW

**Comment by TheArchitect123** [comment]
CreateSignatureAmino has to be a LegacyAminoJson.
If Direct Signing is required then please call the CreateSignature()

**Comment by marcwlux** [comment]
but we are in the CreateSignature method:

public async Task<KeyValuePair<string, SignatureV2>> CreateSignature(SignDoc tx)

**Comment by marcwlux** [comment]
we are calling by default CreateSignature....it has changed somewhere !?

**Comment by TheArchitect123** [comment]
Sorry I forgot to rollback those signature changes. I was trying to test the signature to fix the verification problem.
Please pull the latest main, and try again

**Pull request closed without merging**
